import type { Metadata } from "next";
import ProductPage from "../components/product-page";

export const metadata: Metadata = {
  title: "Thread ID | Lamifor Systems",
  description: "Identify metric and imperial fasteners with a guided, offline workflow built for shop and field work.",
};

export default function ThreadIdPage() {
  return <ProductPage name="Thread ID" eyebrow="Fastener identification" status="Available now on the App Store" icon="/thread-id-icon.png" betaHref="https://apps.apple.com/ca/app/thread-id/id6789962053" primaryActionLabel="Download on the App Store" closingTitle="Put Thread ID to work." closingText="Download Thread ID from the App Store and identify fasteners wherever the job takes you." summary="A guided fastener identification tool for engineers, technicians, mechanics, and tradespeople who need the right information quickly." idea="Fastener identification should not require guesswork, scattered reference charts, or a reliable internet connection. Thread ID turns the process into a clear sequence of practical choices and measurements." audience={["Engineers", "Technicians", "Mechanics", "Tradespeople", "DIY builders"]} features={[{title:"Guided identification",text:"Move through fastener group, type, details, thread system, and measurement in a clear sequence."},{title:"Metric and imperial",text:"Compare common metric and imperial standards without jumping between separate references."},{title:"Practical results",text:"See the most likely match, confidence, useful dimensions, common markings, and practical context."},{title:"Works offline",text:"Use the core identification workflow in workshops, engine rooms, and remote areas."}]} steps={[{number:"01",title:"Choose the family",text:"Start with the broad fastener group and select the closest visual type."},{number:"02",title:"Add details",text:"Answer focused questions about the head, drive, thread, and measurement method."},{number:"03",title:"Review the match",text:"See the most likely identification with dimensions, context, and the reasoning behind the result."}]} screenshots={[{src:"/thread-id-app.png",alt:"Thread ID fastener group selection screen"},{src:"/thread-id-measure.png",alt:"Thread ID measurement method screen"},{src:"/thread-id-result.png",alt:"Thread ID identification result screen"}]} videoGuides={[{title:"Identify your first fastener",text:"A start-to-finish walkthrough of the six-step identification flow."},{title:"Measure diameter and length",text:"How to use a caliper, steel ruler, or an estimate when gathering dimensions."},{title:"Understand your result",text:"How confidence, thread system, pitch, markings, and practical insight work together."}]} />;
}
