import type { Metadata } from "next";
import ProductPage from "../components/product-page";

export const metadata: Metadata = {
  title: "Marine Certificate Tracker | Lamifor Systems",
  description: "Organize vessel certificates, expiry dates, service records, and survey-ready reports in one focused system.",
};

export default function CertificateTrackerPage() {
  return <ProductPage name="Marine Certificate Tracker" eyebrow="Vessel compliance organization" status="Beta" icon="/certificate-tracker-icon.png" betaHref="https://testflight.apple.com/join/Ste9CEP3" summary="A vessel-focused system for organizing certificates, tracking renewal dates, storing service records, and preparing for surveys." idea="Marine certificate tracking often grows into a mix of spreadsheets, folders, reminders, and personal knowledge. Certificate Tracker brings that information together around the company, fleet, vessel, and equipment it belongs to." audience={["Vessel owners", "Marine engineers", "Fleet managers", "Technical superintendents", "Survey preparation teams"]} features={[{title:"Company, fleet, and vessel structure",text:"Keep records organized around the way marine operations are actually managed."},{title:"Expiry and renewal tracking",text:"See upcoming dates clearly and plan renewals before they become urgent."},{title:"Documents and service records",text:"Keep certificate files and supporting service reports connected to the correct record."},{title:"Survey-ready reporting",text:"Prepare clear certificate and service information for reviews, handovers, and surveys."}]} steps={[{number:"01",title:"Build the vessel record",text:"Add the company, fleet, vessel, and the certificates that need to be controlled."},{number:"02",title:"Track the lifecycle",text:"Record issue and expiry dates, attach documents, and keep renewal work visible."},{number:"03",title:"Prepare and report",text:"Review what is current, what needs attention, and assemble useful information for a survey or service period."}]} reportPreview="/certificate-report-preview.png" videoGuides={[{title:"Set up a vessel",text:"Create the company, fleet, and vessel structure before adding certificate records."},{title:"Add and renew a certificate",text:"Enter dates, attach the certificate, and update the record after renewal."},{title:"Prepare for a survey",text:"Review upcoming expiries and produce a clear report for survey planning."}]} />;
}
